index:
    path: /
    controller: App\Controller\HomeController::index
vaisseau_index:
    path: /vaisseau_index
    controller: App\Controller\HomeController::vaisseau_index
vaisseau_form:
    path: /vaisseau_form
    controller: App\Controller\HomeController::vaisseau_form
referencement_index:
    path: /referencement_index
    controller: App\Controller\HomeController::referencement_index
console_bin_index:
    path: /console_bin_index
    controller: App\Controller\HomeController::console_bin_index
extract_map_index:
    path: /extract_map_index
    controller: App\Controller\HomeController::extract_map_index
doctrine_index:
    path: /doctrine_index
    controller: App\Controller\DoctrineController::doctrine_index