index:
    path: /
    controller: App\Controller\HomeController::index
vaisseau_index:
    path: /vaisseau_index
    controller: App\Controller\HomeController::vaisseau_index
vaisseau_form:
    path: /vaisseau_form
    controller: App\Controller\HomeController::vaisseau_form